sudo: false
language: node_js
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - istanbul cover node_modules/mocha/bin/_mocha
after_success:
  - bash <(curl -s https://codecov.io/bash)
