sudo: false
language: node_js
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - pip install codecov
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_success:
  - codecov
